import { BasicContainer } from '@/components/containers/basic-container'
import { H1 } from '@/components/typography/H1'
import { Paragraph } from '@/components/typography/paragraph'
import { Button } from '@/components/ui/button'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <BasicContainer>
      <H1>This what this looks like</H1>
      <Paragraph>Hello what is this all about?</Paragraph>
      <Button>Hello world</Button>
    </BasicContainer>
  )
}
